### ISSUE TITLE
Change unixtime_in_ms type

### ISSUE THREAD

**Issue by manio** [flosse/rust-sun#3]
Hi!
Thank you for your crate! Nice to have this kind of calculations in rust! :)
I am now putting it into my project :)

I want to ask about one thing:
I think it is unable that unixtime_in_ms could be negative, what do you think?
In this case it would be probably better if you change it from i64 to u128.
And u128 is because the rust's Duration::as_millis() is returning u128 type.
So in this case we don't need to cast...

Look how I am obtaining the time:
https://stackoverflow.com/a/44378174

**Comment by flosse** [comment]
> Thank you for your crate! Nice to have this kind of calculations in rust! :)
> I am now putting it into my project :)

great to see this crate in the wild :)
 
> I want to ask about one thing:
> I think it is unable that unixtime_in_ms could be negative, what do you think?

So how do you calculate the position at 1653-02-10T06:13:20.000Z ?

**Comment by manio** [comment]
Ok, got it.
